This workspace coordinates work through graphboard. Rules for every agent:

1. Start work with gb_pull using an owner name in role-instance format (e.g. impl-a, review-b); claim a node, then work ONLY on that node. A gb_note is NOT a claim: ownership begins only when gb_pull returns claimed:. If nothing is pending but nodes of your type await approval, wait or ask the human — do not start working.
2. Load context on demand: the node's inputs plus what gb_query finds relevant; read specific files natively. Never roam the board. Facts injected at gb_pull (servers, ports, URIs) are the current truth about the environment — prefer them over copies frozen in documents.
3. Record progress with gb_note on the node you own — the anchor is yours (current position, how to resume); directives from the conductor arrive as messages at pull and never overwrite it. Finish with gb_submit (declare successors when the workflow expects them). Living documents (proposals, designs) may live in the repo under git; ephemeral reports and verdicts go to the workdir shown by gb_pull. If a node grows too big mid-work, split it with gb_split into self-contained children; each child spec must make sense to a fresh session on its own.
4. Delegated execution: work that runs autonomously (long training, builds, pipelines, external waits) — launch it, record how to check it, then gb_delegate (resources held, check coords in note, check_after) and MOVE ON to the next task; never sit and wait. Before claiming resource-consuming work, run gb_query state=running to see which resources are occupied and do not grab them. When check_after is due, check the execution: harvest it with gb_submit, or gb_reactivate if it needs hands-on attention. Attention is one-at-a-time: keep at most one active node; everything else runs as running.
5. Git discipline (when the repo uses git): keep the baseline shown by gb_pull as your sync point. Commit ONLY files you changed, with explicit pathspec and message "gb <node-id>: summary"; commit your work before gb_submit. NEVER: git add -A, git commit -a, push, merge, rebase, switch branches, reset --hard. The human and other agents also change the tree — if the code changed under you, diff against your baseline and re-orient.
6. If lost, after a session restart, or after context compaction: call gb_status with your owner name to re-orient before doing anything else — it lists your active/running nodes first. gb_pull serves lower priority numbers first; a node's priority is a scheduling hint set by the conductor, not a dependency.
7. Approval, announcements, messages, facts, priority, roles and the grammar belong to the gb conductor role and the human; never act beyond the current node.
